### ISSUE TITLE
Feature: Accepting OpenAI API key on the app

### ISSUE THREAD

**Issue by mehul1011** [yagizhanNY/openai-chatgpt3-clone#10]
This would make users play with the app online.

**Comment by yagizhanNY** [comment]
Actually, users can create their own environment.ts file with their own api key. I explained this at README.md file.

**Comment by mehul1011** [comment]
> Actually, users can create their own environment.ts file with their own api key. I explained this at README.md file. 

No actually on live website, they can type their API key and we store that ethically and let people use chatgpt live.

**Comment by yagizhanNY** [comment]
Oh, okay I get it. Yes, it would be great.

**Comment by mehul1011** [comment]
> Oh, okay I get it. Yes, it would be great.

Hi @yagizhanNY 
Can you please check my PR it's giving some error "Review required
At least 1 approving review is required by reviewers with write access."
I think you have to check from your end.

**Comment by mehul1011** [comment]
> Oh, okay I get it. Yes, it would be great.

Should we securely store that or in localstorage would be fine for now?

**Comment by yagizhanNY** [comment]
I guess yes. But it must be secure. When app is started, we have to check key in local storage. If it is not exists, we have to open some modal screen to get inputs from user.

**Comment by mehul1011** [comment]
> I guess yes. But it must be secure. When app is started, we have to check key in local storage. If it is not exists, we have to open some modal screen to get inputs from user.

Yeah, storing it raw on localstorage would be fine right? Any leakage or privacy issues?

**Comment by mehul1011** [comment]
Implementing this, for now we can just store OPENAI_API_KEY in localstorage and fetch as needed.

**Comment by mehul1011** [comment]
Hi @yagizhanNY,
As you know we are also setting org id, how should we take this in the live app?
API key is fine, we can make a popup and make the user input it, should we also ask for org ID?

**Comment by yagizhanNY** [comment]
Actually, I don't have any idea. Maybe we should test it without org id. If it's still working, we can ignore it.

What do you think?

**Comment by mehul1011** [comment]
> Actually, I don't have any idea. Maybe we should test it without org id. If it's still working, we can ignore it.
> 
> What do you think?

Cool, i will check it out.

**Comment by yagizhanNY** [comment]
Is it completely done with #23 @mehul1011

**Comment by mehul1011** [comment]
> Is it completely done with #23 @mehul1011 

Yes

**Comment by yagizhanNY** [comment]
I am closing this issue but we have to check #25.
