### ISSUE TITLE
Bug: PR always failing when raised

### ISSUE THREAD

**Issue by mehul1011** [yagizhanNY/openai-chatgpt3-clone#13]
Error: 
Review required
At least 1 approving review is required by reviewers with write access.

**Comment by yagizhanNY** [comment]
I couldn't understand why it is happening. The pipeline is working well on my side. I will check it again.

**Comment by mehul1011** [comment]
> I couldn't understand why it is happening. The pipeline is working well on my side. I will check it again. 

Sure thanks

**Comment by mehul1011** [comment]
Hi @yagizhanNY 
For the GitHub action, i wanted to know why you have that deploy action being executed also for raising a PR, i think it should be just for merging into master right?
Correct me if i am wrong.

**Comment by mehul1011** [comment]
Hi @yagizhanNY, i also want to know about envManager.js file built. for ci/cd
How is that locating the src/environments folder if already present?

If not present the i think it's creating it, but upon creating it's giving me error (i am replicating it)

'/home/runner/work/Todo/todo/src/environments/environment.ts' is not a module

**Comment by yagizhanNY** [comment]
Yes, you are right. When we create a merge request to the master, it runs.

**Comment by yagizhanNY** [comment]
> Hi @yagizhanNY, i also want to know about envManager.js file built. for ci/cd How is that locating the src/environments folder if already present?
> 
> If not present the i think it's creating it, but upon creating it's giving me error (i am replicating it)
> 
> '/home/runner/work/Todo/todo/src/environments/environment.ts' is not a module

I have a secret file under my GitHub secrets. This file same as an environment.ts file. I am keeping this file under the secrets because API key etc. must be secret. `envManager.js` file is for create env files when the pipeline is started to run. Normally, your env files must be include into .gitignore file so they shouldn't be existing when you create a merge request.

**Comment by mehul1011** [comment]
> > Hi @yagizhanNY, i also want to know about envManager.js file built. for ci/cd How is that locating the src/environments folder if already present?
> > If not present the i think it's creating it, but upon creating it's giving me error (i am replicating it)
> > '/home/runner/work/Todo/todo/src/environments/environment.ts' is not a module
> 
> I have a secret file under my GitHub secrets. This file same as an environment.ts file. I am keeping this file under the secrets because API key etc. must be secret. `envManager.js` file is for create env files when the pipeline is started to run. Normally, your env files must be include into .gitignore file so they shouldn't be existing when you create a merge request.

Can you elaborate a bit more on this?

I didn't understand the part when you say "file" is stored in github, is it just OpenAI key?


What i didn't understand is, all of the env files are being made upon push into master, ie environment.ts file is being created, but when i tried to replicate your process ie making envManager.js and then it would create src/environments folder and put in the environment files

but while doing this it errors out for me

**'/home/runner/work/Todo/todo/src/environments/environment.ts' is not a module**

it also says 

Jobs:
Run node envManager.js
src does not exist, creating now... /home/runner/work/Todo/todo
environment.ts created successfully /home/runner/work/Todo/todo
undefined
Folder created successfully src/environments    /home/runner/work/Todo/todo

And because of the error above it's giving 


Error: Error: src/app/services/todo.service.ts:4:29 - error TS2306: File '/home/runner/work/Todo/todo/src/environments/environment.ts' is not a module.

(not treating the file as a module i think), did you have any other changes

Actually, i am having src/environments/environment.ts being referenced in many files but since i am not pushing the env files to the repo, it's erroring out here.

**Comment by mehul1011** [comment]
Is there any other workaround for building environment files while building, and not use envManager.js?

**Comment by yagizhanNY** [comment]
I have updated the `deploy.yml` file. After now, pipeline won't executed when merge request is created.

**Comment by mehul1011** [comment]
> I have updated the `deploy.yml` file. After now, pipeline won't executed when merge request is created.

Oh okay nice

**Comment by mehul1011** [comment]
> > I have updated the `deploy.yml` file. After now, pipeline won't executed when merge request is created.
> 
> Oh okay nice

Is there a way to remove the envmanager file and use some other approach?
