### ISSUE TITLE
Style of sidebar

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#20]
![image](https://user-images.githubusercontent.com/41087670/236738685-5a80d4d8-3410-4993-b61c-b5db2461883c.png)

have to fix style issues on sidebar. For example; Open AI API Key and Source Code buttons must be at bottom.

**Comment by mehul1011** [comment]
Have found a solution to this, will be pushing the code once i validate the other issue you raised for blank chatbox
