### ISSUE TITLE
Historical Chat Label Iteration

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#24]
When I type something to ChatGPT and press the `New Chat` button, I expected to create `Chat 2` but it has created `Chat 4`.

![Screenshot 2023-05-28 at 12 37 47](https://github.com/yagizhanNY/openai-chatgpt3-clone/assets/41087670/7d90941c-1bc6-4853-9828-a70f3e96bd87)

**Comment by mehul1011** [comment]
Hi @yagizhanNY,
I will be taking a look at this, i have seen this issue before, it's probably due to the case of how we are storing/managing the chats in localStorage, and someone deletes chat 2-3. I think this issue would come.
