### ISSUE TITLE
Conversation Page Scroll Issue

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#26]
We should able to scroll down and up in conversation screen. We have an issue on conversation page. I can't scroll down. Also it must scroll down automatically when new answer or question comes.

![Screenshot 2023-05-30 at 08 20 25](https://github.com/yagizhanNY/openai-chatgpt3-clone/assets/41087670/ae29cb42-3295-42ad-aec0-b5878982cb92)

**Comment by mehul1011** [comment]
Hi @yagizhanNY,
I have made the changes for this bug.
