### ISSUE TITLE
I found your API key

### ISSUE THREAD

**Issue by itsrn** [yagizhanNY/openai-chatgpt3-clone#30]
When I tried to send a message to ChatGPT through the website, I checked the Network tab in my browser and found out that the OpenAI API Bearer key used in this project is public. (the API key starts with "sk-J3css297iZ00MfiZ57G7T3BlbkFJ")

I suggest you to regenerate this API key and create an API endpoint in the website (for example: /api/generate) that sends the request to OpenAI's server. That way, your API key isn't shown to anyone.

Also, you should fix that user's won't be able to use the model without an API key, or at least limit the API endpoint for around 50 requests per day by IP in order to not reach the limit of your API key.

**Comment by yagizhanNY** [comment]
Hi @itsrn 

Thanks for this critical feedback. I saw the problem and disabled my API key for now. I will fix it asap. Also thanks for your suggestions.

**Comment by itsrn** [comment]
Your welcome! I am happy to know that you disabled your API key for now. Have a great day.

**Comment by yagizhanNY** [comment]
you too!

**Comment by yagizhanNY** [comment]
Now, user must enter their own api key before the chat. It's still visible on headers but not mine anymore :)
