### ISSUE TITLE
Implement conversation history

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#4]
It might be good if we can store conversations in local storage.

**Comment by mehul1011** [comment]
@yagizhanNY That would be a good idea, currently it's not supported, you meant as we can fetch from the local store what the user had as their conversation previously and it will be brought back if the user later visits the app back?

**Comment by mehul1011** [comment]
@yagizhanNY 
Also, I was just playing around with ChatGPT with my own API key, it didn't remember any old conversations that I had, even the immediate previous ones.

Let me know how would this actually work, like how the previous conversations need to be passed to OpenAI API so that it reacts with those previous conversations being loaded in it.
This would be a critical feature, you can even create an issue for this, and we may get some traffic 😁

**Comment by yagizhanNY** [comment]
> @yagizhanNY That would be a good idea, currently it's not supported, you meant as we can fetch from the local store what the user had as their conversation previously and it will be brought back if the user later visits the app back?

<img width="900" alt="Screenshot 2023-04-05 at 20 27 28" src="https://user-images.githubusercontent.com/41087670/230157714-273946e2-677a-4f39-ad32-5e1794119751.png">

Maybe we can implement conversation history like this. User can start new conversation when it wants and we can store old conversations in sidebar like as screenshot.

What do you think?

**Comment by yagizhanNY** [comment]
> @yagizhanNY Also, I was just playing around with ChatGPT with my own API key, it didn't remember any old conversations that I had, even the immediate previous ones.
> 
> Let me know how would this actually work, like how the previous conversations need to be passed to OpenAI API so that it reacts with those previous conversations being loaded in it. This would be a critical feature, you can even create an issue for this, and we may get some traffic 😁

Yes you are right. ChatGPT does not have built-in conversation history feature also does not have session handling. If you want to reminder previous conversation to the ChatGPT, you have to send every conversation at once before new message. It might effect the cost. As you know ChatGPT is counting tokens for costing. 

We have to think about it. But first we can only store conversation local and show these in sidebar.

**Comment by mehul1011** [comment]
> > @yagizhanNY Also, I was just playing around with ChatGPT with my own API key, it didn't remember any old conversations that I had, even the immediate previous ones.
> > Let me know how would this actually work, like how the previous conversations need to be passed to OpenAI API so that it reacts with those previous conversations being loaded in it. This would be a critical feature, you can even create an issue for this, and we may get some traffic 😁
> 
> Yes you are right. ChatGPT does not have built-in conversation history feature also does not have session handling. If you want to reminder previous conversation to the ChatGPT, you have to send every conversation at once before new message. It might effect the cost. As you know ChatGPT is counting tokens for costing.
> 
> We have to think about it. But first we can only store conversation local and show these in sidebar.

Oh okay, that's very insightful i didn't have any idea about this, sending the whole previous conversation would definitely be costly.

**Comment by mehul1011** [comment]
Sure i will look into the sidebar, i am also going through some existing code on how you have approached the problem till now.
By that time can we merge this branch, and let's have a separate branch for the new sidebar? And if possible can you also mention how are you deploying, whenever you are available please let me know this in detail if possible, it would be great learning for me.

**Comment by yagizhanNY** [comment]
> Sure i will look into the sidebar, i am also going through some existing code on how you have approached the problem till now. By that time can we merge this branch, and let's have a separate branch for the new sidebar? And if possible can you also mention how are you deploying, whenever you are available please let me know this in detail if possible, it would be great learning for me.

I created an issue (#5) for this. I will create a ci/cd pipeline in this repo to automate deployment process. You can check how can I deploy the app to the firebase from this pipeline.

You can play with sidebar if you want. When you finished, you can open a new pr.

**Comment by mehul1011** [comment]
> > Sure i will look into the sidebar, i am also going through some existing code on how you have approached the problem till now. By that time can we merge this branch, and let's have a separate branch for the new sidebar? And if possible can you also mention how are you deploying, whenever you are available please let me know this in detail if possible, it would be great learning for me.
> 
> I created an issue (#5) for this. I will create a ci/cd pipeline in this repo to automate deployment process. You can check how can I deploy the app to the firebase from this pipeline.
> 
> You can play with sidebar if you want. When you finished, you can open a new pr.

Sure that would be great.

**Comment by mehul1011** [comment]
> > > Sure i will look into the sidebar, i am also going through some existing code on how you have approached the problem till now. By that time can we merge this branch, and let's have a separate branch for the new sidebar? And if possible can you also mention how are you deploying, whenever you are available please let me know this in detail if possible, it would be great learning for me.
> > 
> > 
> > I created an issue (#5) for this. I will create a ci/cd pipeline in this repo to automate deployment process. You can check how can I deploy the app to the firebase from this pipeline.
> > You can play with sidebar if you want. When you finished, you can open a new pr.
> 
> Sure that would be great.

Currently working on the sidenavbar, do you suggest just using tailwind, or tailwind + some library (ionic), or just plain CSS/JS/HTML design

**Comment by yagizhanNY** [comment]
> > > > Sure i will look into the sidebar, i am also going through some existing code on how you have approached the problem till now. By that time can we merge this branch, and let's have a separate branch for the new sidebar? And if possible can you also mention how are you deploying, whenever you are available please let me know this in detail if possible, it would be great learning for me.
> > > 
> > > 
> > > I created an issue (#5) for this. I will create a ci/cd pipeline in this repo to automate deployment process. You can check how can I deploy the app to the firebase from this pipeline.
> > > You can play with sidebar if you want. When you finished, you can open a new pr.
> > 
> > 
> > Sure that would be great.
> 
> Currently working on the sidenavbar, do you suggest just using tailwind, or tailwind + some library (ionic), or just plain CSS/JS/HTML design

It would be great if we just use Tailwind.

**Comment by yagizhanNY** [comment]
I have implemented something for local storage to store conversation history. It's working well. It is storing when the new message added to the list. Messages are stills on the screen when user press refresh. You can continue with [this](/yagizhanNY/openai-chatgpt3-clone/tree/local-conversation-history) branch. @mehul1011

**Comment by mehul1011** [comment]
> I have implemented something for local storage to store conversation history. It's working well. It is storing when the new message added to the list. Messages are stills on the screen when user press refresh. You can continue with [this](/yagizhanNY/openai-chatgpt3-clone/tree/local-conversation-history) branch. @mehul1011 

Awesome, i will pull the changes. Thanks @yagizhanNY

**Comment by mehul1011** [comment]
Hi, @yagizhanNY 
I have implemented the localStorage feature (I am also trying to use NgRx in a very simple way just wanted to give it a shot how it works), but not entirely for all Chat Lists, since we have not implemented that multiple features i am having some difficulties, also what do you think when we implement the multiple chats we would need to fetch the data from LocalStorage with some unique IDs, where do you suggest i should make it (should i use UUID)?

**Comment by yagizhanNY** [comment]
In my opinion, we can handle this with buttons. We need two buttons. One for clear current conversation other is for save the conversation. When user click to `save current conversation` button we can add this message list to the side bar. What do you think? In this case we don't need any unique id. Maybe in the future, we can store these conversations in database with session management. User can log in and fetch their historical conversation.

**Comment by mehul1011** [comment]
> In my opinion, we can handle this with buttons. We need two buttons. One for clear current conversation other is for save the conversation. When user click to `save current conversation` button we can add this message list to the side bar. What do you think? In this case we don't need any unique id. Maybe in the future, we can store these conversations in database with session management. User can log in and fetch their historical conversation. 

Yeah development wrt this approach would become easy, but i think there would be too many clicks/user mouse movements required.

I was just thinking always save the conversation and have the option of deleting it from sidebar.

Let me know your thoughts

**Comment by mehul1011** [comment]
Currently working on this (implementing multiple chats), should we take it with this issue number, since this is the history-related thing we discussed? Let me know if i should create a new issue for multiple chats

And any inputs that you can provide for implementing the chats, i have implemented the UI for it completely and some bugs are left off while dealing with localStorage and NgRx store logic.

**Comment by yagizhanNY** [comment]
Actually, I don't have any inputs regarding this issue. I could not find a chance to search about this issue. 

We can continue on this issue in my opinion. 

What is the last status of this feature? Did you implement anything?

**Comment by mehul1011** [comment]
Hi @yagizhanNY,
This feature seems to be complete, just some minor bugs i see, I will try working on those.
We can probably close this issue.

**Comment by mehul1011** [comment]
> Hi @yagizhanNY,
> This feature seems to be complete, just some minor bugs i see, I will try working on those.
> We can probably close this issue.

Hi @yagizhanNY please let me know anything that you prioritising from the existing issues, or concentrate on mobile version fix?
