### ISSUE TITLE
Create ci/cd pipeline for deploying

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#5]

**Comment by yagizhanNY** [comment]
@mehul1011 it's ready, you can check.

**Comment by mehul1011** [comment]
> @mehul1011 it's ready, you can check.

Thanks for updating @yagizhanNY, I will go through it. I will start the navbar today night IST time.

**Comment by mehul1011** [comment]
@yagizhanNY I am going through CI/CD creation, I didn't understand it completely, is there any documentation/video that can show these steps?

I checked on YT it had Docker + GitHub action, a bit confused about what exactly you have used, is it Actions + Firebase?

**Comment by yagizhanNY** [comment]
> @yagizhanNY I am going through CI/CD creation, I didn't understand it completely, is there any documentation/video that can show these steps?
> 
> I checked on YT it had Docker + GitHub action, a bit confused about what exactly you have used, is it Actions + Firebase?

In my opinion, if you learned the concept of CI/CD pipelines you can use this in different platforms such as GitHub actions. [This](https://www.youtube.com/watch?v=R8_veQiYBjI ) video is a good start point to learn CI/CD pipelines.
