### ISSUE TITLE
Fix code view issue on mobile

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#6]
We have size issue on mobile.

![WhatsApp Image 2023-04-06 at 13 20 13](https://user-images.githubusercontent.com/41087670/230349482-7d2dd9a9-84db-41d1-b99a-0efcdecade93.jpeg)

**Comment by mehul1011** [comment]
Will be fixed with my changes for sidebar implementation, currently working on mobile view, thinking to have a hamburger at top to open that same sidebar
