### ISSUE TITLE
Add Toast messages for exceptions

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#7]
It would be great if we can show errors as a toast message.

For example;
![image](https://user-images.githubusercontent.com/41087670/230552839-9c09a838-c90b-4197-a8ee-85ec702d59c7.png)

- Must be a separate component (using only Tailwind not 3rd party library).
- Must have pop-up animation.

**Comment by mehul1011** [comment]
Would be amazing @yagizhanNY, can you mention which all cases should we cover?

**Comment by yagizhanNY** [comment]
Every exceptions which comes from OpenAI must be covered.

**Comment by mehul1011** [comment]
> Every exceptions which comes from OpenAI must be covered.

Okay sure @yagizhanNY 
I will go over their documentation, i still need to see how we are implementing the current logic for showing chatgpt message. I will do this today.

From tomorrow will start with any improvement that we can have like the displaying the results letter by letter of chatgpt.

And also chat component with local storage improvement.
